# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipeline-to-AWS-ElastikBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "petyaev-flask-app-packages"
  EB_APPLICATION_NAME       : "MyFlask"
  EB_ENVIRONMENT_NAME       : "MyFlask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "eu-north-1"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone my repo
      - uses: actions/checkout@v3

      
      - name: Create ZIP deployment package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME  }} ./ -x *.git*

   
